### ISSUE TITLE
env.reset() error

### ISSUE THREAD

**Issue by pinyaras** [Duncanswilson/q-routing-protocol#2]
Hello,
I tried to run the code but I got the following error.

ubuntu@sdnhubvm:~/ML/RL/q-routing-protocol[10:01] (master)$ python do_q_learning.py 
Traceback (most recent call last):
  File "do_q_learning.py", line 69, in <module>
    main()
  File "do_q_learning.py", line 17, in main
    state_pair = env.reset()
  File "/home/ubuntu/ML/RL/gym/gym/core.py", line 70, in reset
    raise NotImplementedError
NotImplementedError

Do i have to install any additional env packages?

Thank you,
Pinyarash P.

**Comment by pinyaras** [comment]
I figured it out.

Thanks

**Comment by ManishaDesham** [comment]
Hi Pinyarash ,

We are encountering a similar issue with "line 70, in reset
raise NotImplementedError
NotImplementedError" in our program. We wanted to know how did you go about fixing it? Did you install any additional packages or followed some steps. Please share the steps. 

Thanks..

**Comment by farhankhan43** [comment]
Hi Pinyaras,

I am having a similar error. Can you explain how you corrected it.

**Comment by pinyaras** [comment]
@ManishaDesham  @farhankhan43 
Sorry, I just saw this post. 
You need to change the from env.reset to env._reset().
If you need more helps, you can contact me to this email ppinyarash@gmail.com.

Thanks

**Comment by farhankhan43** [comment]
Thanks Manisha.

Actually I implemented a different version now.

**Comment by farhankhan43** [comment]
Thanks Pinyarash,

I am doing it another way now.
