### ISSUE TITLE
need help on env.reset() error fix:

### ISSUE THREAD

**Issue by ManishaDesham** [Duncanswilson/q-routing-protocol#3]
Hi Pinyarash ,

We are encountering a similar issue with "line 70, in reset
raise NotImplementedError
NotImplementedError" in our program. We wanted to know how did you go about fixing it? Did you install any additional packages or followed some steps. Please share the steps.

Thanks..

**Comment by ManishaDesham** [comment]
figured it out. thanks.

**Comment by farhankhan43** [comment]
Hi Manish,
Can you tell what was the problem

**Comment by astride09** [comment]
just removed underscores in _step, _render, etc in the simulator.py file. it worked for me, i hope that it will work also for you
